### ISSUE TITLE
gencode.v16_intronExonSIannot.gtf not in the repository.

### ISSUE THREAD

**Issue by sameet** [churchmanlab/human_NETseq#1]
Hi,

I am trying to run the script, however, the `gencode.v16_intronExonSIannot.gtf` is not in the cloned repository.  Do I need to provide the path to this in the script.  If so, it is not entirely clear from the script itself.

Sameet

**Comment by dylanmmarshall** [comment]
I've uploaded an alternative file that is named slightly differently: `gencode.v16_intronExonSpliceIntermAnnotation_ALL_forHTSeq_noParenthesis_3bpAt3end_{1, 2}.gtf` The restriction on file size forced me to split the file to two, it is necessary to recombine them with:

`>>> cat gencode.v16_intronExonSpliceIntermAnnotation_ALL_forHTSeq_noParenthesis_3bpAt3end_1.gtf gencode.v16_intronExonSpliceIntermAnnotation_ALL_forHTSeq_noParenthesis_3bpAt3end_2.gtf > gencode.v16_intronExonSpliceIntermAnnotation_ALL_forHTSeq_noParenthesis_3bpAt3end.gtf`
