### ISSUE TITLE
Two more files seem required but are missing.

### ISSUE THREAD

**Issue by sameet** [churchmanlab/human_NETseq#2]
In the script there are two more files required, `PP_coord.txt` and `GB_coord.txt`.  I can see the `.txt.gz` version for both of these files.  Should these be unzipped using `zcat` so that they can be used properly?

**Comment by dylanmmarshall** [comment]
All compression was done with default parameters, `gunzip` and `zcat` are the same in that regard. Future questions will ideally indicate that initiative was taken to answer them, please and thank you.
